### ISSUE TITLE
Path in Visit, no curved meshes seen in Visit plots despite higher order calculations 

### ISSUE THREAD

**Issue by cjoycd** [CEED/Laghos#10] opened 2018-02-07 12:11 UTC
The files to load in Visit plotting software basically writes in a directory results/Lagos, specified in Lagos.cpp through character "*basename".  However, while trying to open the files "Laghos_00***.mfem_root" in the results directory with Visit, the path detected by the Visit and path defined in the files "Laghos_00***.mfem_root" get conflicted. I have get rid of this issue in a crude way by changing the character value "*basename" in Lagos.cpp to "Lagos". Then the results dumped in Lagos directory will be moved to directory "results" and open Visit in this directly to plot. This avoids the conflicts of the paths.

Another issue found is that after running higher order simulations using a command say "mpirun -np 4 laghos -p 1 -m data/square01_quad.mesh -rs 4 -tf 0.5 -ok 4 -ot 3 -visit", the plots of the mesh does not show as higher order (curved) meshes in Visit. Is there something I am missing while running the code?

Thanks in advance for the help

**Comment by tzanio** [comment] 2018-02-07 14:13
Hi @cjoycd 

I can't reproduce the first issue you are reporting -- are you using a recent version of VisIt? For me, after I run Laghos with `-visit`, I can just `File`/`Open File` in VisIt and select the `Laghos_*.mfem_root` database.

Regarding the second issue, you need to use the `Multires` control in VisIt to visualize high-order data. This is under `Operators` / `Selection` and you increase it to get better curvature representation. For physics fields, this is sufficient to see the variation in each element. To see the high-order curved mesh:

1. Plot `Subset` / `blocks`
2. Double-click on the plot and select the `Wireframe` option.
3. Select `Operators` / `Selection` / `MultiresControl` for this plot
4. Open the little triangle next to `Subset` and double-click the `MultiresControl`
5. Increase the multires resolution.

Hope this helps,
Tzanio

cc: @vladotomov, @cyrush

**Comment by cjoycd** [comment] 2018-02-08 04:20
Dear Tzanio,

Thank you for your help...

I am using Visit version 2.10.0.
The curved mesh plotting issue is resolved now.
However, the path issue remains, may be the version issue. Its fine!

Is there any chance for an axis-symmetric (RZ) version of the Lagos code to
be released in near future ?

With kind Regards
--Sijoy C. D.

**Comment by cyrush** [comment] 2018-02-08 15:26
@cjoycd VisIt 2.10.0 is from Oct 2015.
VisIt2.13.0 is the latest, and I believe it has a newer version of MFEM, would it be possible to see if the newer version of VisIt resolves the issue?

**Comment by cjoycd** [comment] 2018-02-09 03:40
Dear Cyrus Harrison,

OK, I will try to install latest Visit version and will see ... Thank you
very much..

Regards

**Comment by vladotomov** [comment] 2018-02-23 00:23
Hi @cjoycd 

We're currently not planning to add RZ functionality. I'm closing this, free free to reopen it you encounter other Visit issues.

Best, Vladimir

**Closed as completed** 2018-02-23 00:23 UTC
Labels: usage

**Comment by cjoycd** [comment] 2018-02-23 04:17
Dear Vladimir,

OK, Thanks!

Regads
​-- ​
S
​ijoy

​
------------------------------------------------------------
